# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.wxcsdb88.com
date_format: "ordinal"
title: 路漫漫兮
subtitle: "码上人生"
description: "王鑫的个人博客"
keywords: 路漫漫兮, XIN WANG, wxcsdb88, futurever
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: XIN WANG
organization: futurever.com
organization_url: http://www.futurever.com
github_username: wxcsdb88
location: BeiJing, China
email: wangxin@futurever.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wxcsdb88/wxcsdb88.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: wxcsdb88
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wxcsdb88
    repo: blog-comments
    oauth:
        client_id: 9f651eb6e49a0d3b4d98
        client_secret: 64f2c9ce0051f2f25cd7f82e1d377050e27d4dc1
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-104142700-1
